# 1. Opérations matricielles
### Niveau Débutant : Création et manipulation de matrices
Nous allons commencer par la création de matrices avec NumPy et quelques opérations de base.

In [1]:
import numpy as np  # Importation de la bibliothèque NumPy

# Création d'une matrice 2x2 avec des nombres entiers
matrice = np.array([[1, 2], [3, 4]])
print("Matrice 2x2 :\n", matrice)

# Accès aux éléments de la matrice
element = matrice[0, 1]  # Accès à l'élément à la première ligne et deuxième colonne
print("Élément [0, 1] :", element)  # Affiche 2

# Transposition d'une matrice
transposee = np.transpose(matrice)
print("Matrice transposée :\n", transposee)  # Affiche [[1 3], [2 4]]


Matrice 2x2 :
 [[1 2]
 [3 4]]
Élément [0, 1] : 2
Matrice transposée :
 [[1 3]
 [2 4]]


In [5]:
matrice1 = np.array([[5,6],[14,-3]])

### Niveau Intermédiaire : Opérations matricielles élémentaires
À ce niveau, nous allons effectuer des opérations comme la multiplication, l'inversion, et d'autres opérations classiques sur les matrices.

In [7]:
# Multiplication matricielle
matrice_2 = np.array([[5, 6], [7, 8]])
produit_matriciel = np.dot(matrice, matrice_2)
print("Produit matriciel :\n", produit_matriciel)  # Affiche [[19 22], [43 50]]

# Déterminant d'une matrice
determinant = np.linalg.det(matrice)
print("Déterminant de la matrice :", determinant)  # Affiche -2.0

# Inversion de matrice (si elle est inversible)
matrice_inversible = np.linalg.inv(matrice)
print("Matrice inversée :\n", matrice_inversible)  # Affiche [[-2.  1.], [1.5 -0.5]]


Produit matriciel :
 [[19 22]
 [43 50]]
Déterminant de la matrice : -2.0000000000000004
Matrice inversée :
 [[-2.   1. ]
 [ 1.5 -0.5]]


### Niveau ++ : Décomposition et solutions de systèmes d'équations linéaires
Nous allons explorer des concepts plus avancés comme la décomposition en valeurs propres et la résolution de systèmes d'équations linéaires.

In [9]:
# Décomposition en valeurs propres
valeurs_propres, vecteurs_propres = np.linalg.eig(matrice)
print("Valeurs propres :", valeurs_propres)  # Affiche les valeurs propres
print("Vecteurs propres :\n", vecteurs_propres)  # Affiche les vecteurs propres associés

# Résolution d'un système d'équations linéaires : A*x = b
A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
solution = np.linalg.solve(A, b)
print("Solution du système A*x = b :", solution)  # Affiche [2. 3.]


Valeurs propres : [-0.37228132  5.37228132]
Vecteurs propres :
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
Solution du système A*x = b : [2. 3.]


### 2. Les fonctions incontournables
Niveau Débutant : Fonctions mathématiques de base
Nous allons découvrir certaines fonctions mathématiques de base intégrées dans NumPy.

In [11]:
# Somme et produit des éléments d'une matrice
somme_elements = np.sum(matrice)
print("Somme des éléments de la matrice :", somme_elements)  # Affiche 10

produit_elements = np.prod(matrice)
print("Produit des éléments de la matrice :", produit_elements)  # Affiche 24

# Calcul de la moyenne, médiane et écart-type
moyenne = np.mean(matrice)
print("Moyenne :", moyenne)  # Affiche 2.5

ecart_type = np.std(matrice)
print("Écart-type :", ecart_type)  # Affiche 1.118033988749895

# si loi normale (ou distribution gaussienne) => Règle des 68%-95%-99.7% sur [μ−σ,μ+σ] - [μ−2σ,μ+2σ] - [μ−3σ,μ+3σ]


Somme des éléments de la matrice : 10
Produit des éléments de la matrice : 24
Moyenne : 2.5
Écart-type : 1.118033988749895


### Niveau Intermédiaire : Fonctionnalités statistiques et logiques
À ce niveau, nous allons approfondir l'utilisation des fonctions statistiques et logiques.

In [13]:
# Minimum, maximum et médiane des éléments d'une matrice
minimum = np.min(matrice)
print("Minimum de la matrice :", minimum)  # Affiche 1

maximum = np.max(matrice)
print("Maximum de la matrice :", maximum)  # Affiche 4

# Fonctions logiques (comparaison)
superieur_a_2 = matrice > 2
print("Éléments supérieurs à 2 :\n", superieur_a_2)  # Affiche un tableau booléen

# Comptage d'éléments selon une condition
comptage = np.sum(matrice > 2)
print("Nombre d'éléments supérieurs à 2 :", comptage)  # Affiche 2


Minimum de la matrice : 1
Maximum de la matrice : 4
Éléments supérieurs à 2 :
 [[False False]
 [ True  True]]
Nombre d'éléments supérieurs à 2 : 2


In [15]:
matrice > 2

array([[False, False],
       [ True,  True]])

### Niveau ++ : Fonctions avancées de manipulation
Nous allons découvrir des fonctions de manipulation plus avancées, comme les fonctions d'interpolation et les transformations FFT.

In [19]:
# Interpolation linéaire
x = np.array([0, 1, 2])
y = np.array([0, 1, 4])
nouveau_x = np.array([0.5, 1.5])
interpolation = np.interp(nouveau_x, x, y)
print("Interpolation linéaire pour x=0.5 et x=1.5 :", interpolation)  # Affiche [0.5 2.5]

# Transformation de Fourier rapide (FFT)
signal = np.array([0, 1, 0, -1])
fft = np.fft.fft(signal)
print("Transformée de Fourier du signal :", fft)


Interpolation linéaire pour x=0.5 et x=1.5 : [0.5 2.5]
Transformée de Fourier du signal : [0.+0.j 0.-2.j 0.+0.j 0.+2.j]


In [22]:
""" éliminer la ligne du dessus inutile """

' éliminer la ligne du dessus inutile '

# 3. Entrées/Sorties et formats de fichiers
### Niveau Débutant : Lecture et écriture de fichiers avec NumPy
NumPy offre des fonctions simples pour lire et écrire des fichiers sous différents formats.

In [24]:
# Sauvegarder un tableau NumPy dans un fichier texte
np.savetxt('data/matrice.txt', matrice, fmt='%d')
print("Matrice sauvegardée dans 'matrice.txt'.")

# Charger un tableau depuis un fichier texte
matrice_chargee = np.loadtxt('data/matrice.txt', dtype=np.int32)
print("Matrice chargée depuis 'matrice.txt' :\n", matrice_chargee)


Matrice sauvegardée dans 'matrice.txt'.
Matrice chargée depuis 'matrice.txt' :
 [[1 2]
 [3 4]]


### Niveau Intermédiaire : Formats natifs NumPy
NumPy propose également un format binaire plus performant, .npy, pour stocker des données.

In [26]:
# Sauvegarder un tableau au format .npy
np.save('data/matrice.npy', matrice)
print("Matrice sauvegardée dans 'matrice.npy'.")

# Charger un tableau depuis un fichier .npy
matrice_chargee_npy = np.load('data/matrice.npy')
print("Matrice chargée depuis 'matrice.npy' :\n", matrice_chargee_npy)


Matrice sauvegardée dans 'matrice.npy'.
Matrice chargée depuis 'matrice.npy' :
 [[1 2]
 [3 4]]


### Niveau Expert : Gestion des formats scientifiques (NetCDF, HDF5, Matlab)
#### a) NetCDF :
NetCDF est un format populaire pour le stockage de données scientifiques multidimensionnelles.

In [28]:
import netCDF4 as nc # Le module est importé sous l'alias nc pour simplifier l'utilisation des fonctions.

# Créer un fichier NetCDF et y stocker un tableau

# Création d'un fichier NetCDF et stockage de données en mode w (write) au format METCDF4
ncfile = nc.Dataset('data/exemple.nc', mode='w', format='NETCDF4')
# Création d'une dimension similaire aux axes dans les tableaux multidimensionnels. Elles définissent la taille et la structure des variables dans le fichier.
dim1 = ncfile.createDimension('dim1', 2)  # La dimension est ici statique (taille fixe de 2).
# Création d'une variable associée à la dimension
var = ncfile.createVariable('var', np.int32, ('dim1',)) # La variable est de type np.int32 (entiers 32 bits), donc elle stockera des entiers sur 32 bits, associé à dim1
# Stockage de données dans la variable
var[:] = matrice[0]  # var[:] on veut accéder à toute la variable (dans ce cas, à toutes les valeurs le long de la dimension 'dim1'). matrice[0] = 1er ligne de matrice
# fermeture du fichier NetCDF
ncfile.close()

# Lire un fichier NetCDF
ncfile = nc.Dataset('data/exemple.nc', mode='r')
donnees = ncfile.variables['var'][:]
print("Données du fichier NetCDF :", donnees)  # Affiche [1 2]
ncfile.close()


Données du fichier NetCDF : [1 2]


#### b) HDF5 :
HDF5 est un format utilisé pour le stockage de grandes quantités de données scientifiques.

In [ ]:
import h5py

# Créer un fichier HDF5 et y stocker un tableau
with h5py.File('data/exemple.h5', 'w') as h5file:
    h5file.create_dataset('dataset', data=matrice)

# Lire un fichier HDF5
with h5py.File('data/exemple.h5', 'r') as h5file:
    donnees = h5file['dataset'][:]
    print("Données du fichier HDF5 :\n", donnees)  # Affiche la matrice


#### c) MATLAB :
Le format MATLAB permet d'échanger des données entre NumPy et MATLAB.

In [30]:
from scipy.io import savemat, loadmat

# Sauvegarder un tableau au format MATLAB
savemat('data/matrice.mat', {'data/matrice': matrice})
print("Matrice sauvegardée dans 'matrice.mat'.")

# Charger un tableau depuis un fichier MATLAB
donnees_matlab = loadmat('data/matrice.mat')
print("Données du fichier MATLAB :\n", donnees_matlab['data/matrice'])


Matrice sauvegardée dans 'matrice.mat'.
Données du fichier MATLAB :
 [[1 2]
 [3 4]]
