<a href="https://colab.research.google.com/github/MachineLearnia/Python-Machine-Learning/blob/master/11%20-%20Numpy%20%3A%20Indexing%2C%20Slicing%2C%20Boolean%20Indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 11/30 Numpy : Slicing et Indexing

In [2]:
import numpy as np

## Indexing et Slicing
Le fonctionnement est le meme que pour les listes

In [3]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A)

[[1 2 3]
 [4 5 6]]


In [3]:
# Pour acceder a la ligne 0, colonne 1
A[0, 1] 

np.int64(2)

In [4]:
# Pour selectionner les blocs de la ligne (0-1) colonne (0-1)
A[0:2, 0:2]

array([[1, 2],
       [4, 5]])

In [5]:
A[0:2, 0:2] = 10
print(A)

[[10 10  3]
 [10 10  6]]


## Boolean Indexing

In [6]:
A = np.array([[1, 2, 3], [4, 5, 6]])
 
print(A<5) # masque booléen
 
print(A[A < 5]) # sous-ensemble filtré par le masque booléen
 
A[A<5] = 4 # convertit les valeurs sélectionnées.
print(A)

[[ True  True  True]
 [ True False False]]
[1 2 3 4]
[[4 4 4]
 [4 5 6]]


## Exercices et Solutions
### Exercice 1

Remplir les 4 blocs du milieux par des "1"

In [7]:
B = np.zeros((4, 4))
B

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
# SOLUTION
B[1:3 , 1:3] = 1
B

array([[0., 0., 0., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 0., 0., 0.]])

### Exercice 2
Remplir le tableau de "1" (une ligne sur deux, une colonne sur deux)

In [9]:
C = np.zeros((5, 5))
C

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
# SOLUTION
C[::2, ::2] = 1
C

array([[1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1.]])